/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jlfqbsscxvwhunhidsdx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsZnFic3NjeHZ3aHVuaGlkc2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0ODM5MjcsImV4cCI6MjA3MjA1OTkyN30.S3H-gEGu7iqISS4BcfLi0qH0Vw_GdGB6aBo4IE6X-7E"